In [49]:
import pandas as pd

In [50]:
schema = pd.read_csv('survey_results_schema.csv',encoding='utf-8')
survey = pd.read_csv('survey_results_public.csv',encoding='utf-8')

C:\Users\1\AppData\Local\Temp\ipykernel_6380\3254981377.py:2: DtypeWarning: Columns (0: JobSatPoints_15_TEXT, 1: DatabaseHaveEntry, 2: DevEnvHaveEntry, 3: SOTagsHaveEntry, 4: SOTagsWant Entry, 5: OfficeStackWantEntry, 6: CommPlatformHaveEntr, 7: CommPlatformWantEntr, 8: SO_Actions_15_TEXT, 9: AIAgentOrchestration, 10: AIAgentObsWrite) have mixed types. Specify dtype option on import or set low_memory=False.
  survey = pd.read_csv('survey_results_public.csv',encoding='utf-8')

In [51]:
pd.set_option('display.max_columns', None)

In [52]:
survey.head(3)

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,14.0,"Developer, mobile",20 to 99 employees,People manager,Remote,"Yes, I influenced the purchase of a substantia...",Work,10.0,7.0,9.0,6.0,3.0,11.0,12.0,1.0,8.0,14.0,NaN,15.0,7.0,8.0,12.0,11.0,1.0,6.0,13.0,3.0,16.0,NaN,Fintech,3.0,1.0,4.0,9.0,5.0,10.0,12.0,11.0,2.0,6.0,7.0,13.0,14.0,15.0,8.0,NaN,I'm not sure,I have neither consider or transitioned into a...,7.0,3.0,Ukraine,EUR European Euro,52800.0,Yes,Bash/Shell (all shells);Dart;SQL,Dart,Dart,NaN,NaN,Yes,Cloud Firestore;PostgreSQL,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Cloudflare;Firebase;...,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Android Studio;Notepad++;Visual Studio;Visual ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;Android,Windows;MacOS;Android;iOS;iPadOS,Confluence;GitHub;GitLab;Jira;Markdown File,Markdown File,Markdown File,NaN,NaN,"Stack Overflow;Reddit;GitHub (public projects,...",NaN,NaN,NaN,NaN,Yes,openAI GPT (chatbot models);openAI Image gener...,NaN,NaN,NaN,NaN,Yes,A few times per week,Between 5 and 10 years,I have never participated in Q&A on Stack Over...,NaN,1.0,NaN,6.0,2.0,3.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools monthly or infrequently",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning about a codebase;Writing code;Search ...,Project planning;Deployment and monitoring;Lea...,Documenting code;Debugging or fixing code;Test...,NaN,NaN,"AI solutions that are almost right, but not quite",No,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,NaN,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,The cost of using certain AI agent platforms i...,NaN,NaN,NaN,NaN,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,10.0,"Developer, back-end",500 to 999 employees,Individual contributor,"Hybrid (some in-person, leans heavy to flexibi...",No,Personal Project,13.0,1.0,2.0,9.0,4.0,3.0,12.0,5.0,7.0,14.0,NaN,14.0,1.0,13.0,10.0,9.0,3.0,4.0,2.0,5.0,15.0,NaN,Retail and Consumer Services,10.0,8.0,3.0,9.0,12.0,1.0,6.0,2.0,11.0,4.0,7.0,13.0,14.0,15.0,5.0,NaN,I'm not sure,I have transitioned into a new career and/or i...,6.0,5.0,Netherlands,EUR European Euro,90000.0,Yes,Java,Java;Python;Swift,Java,NaN,NaN,Yes,Dynamodb;MongoDB,Dynamodb;MongoDB,Dynamodb;MongoDB,NaN,NaN,Yes,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,Yes,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;iOS;iPadOS,MacOS,Confluence;GitHub;Jira,Confluence;GitHub;Jira,Confluence;GitHub;Jira,NaN,NaN,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,Not sure/can't remember,Multiple times per day,Between 10 and 15 years,"Infrequently, less than once per year",Chat (people);Message Boards;Long-form article...,6.0,NaN,5.0,8.0,2.0,4.0,9.0,10.0,11.0,15.0,NaN,"Yes, somewhat",About half of the time,"Yes, I use AI tools weekly",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning new concepts or technologies,Learning about a codebase;Project planning;Com...,Writing code;Documenting code;Debugging or fix...,NaN,NaN,"AI solutions that are almost right, but not qu...",No,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,12.0,"Developer, front-end",NaN,NaN,NaN,No,Work,12.0,2.0,3.0,7.0,5.0,10.0,13.0,1.0,4.0,14.0,NaN,8.0,1.0,2.0,12.0,13.0,3.0,9.0,4.0,11.0,15.0,NaN,Software Development,9.0,6.0,7.0,11.0,8.0,12.0,1.0,5.0,2.0,4.0,3.0,13.0,14.0,15.0,10.0,NaN,No,I have transitioned into a new career and/or i...,3.0,3.0,Ukraine,UAH Ukrainian hryvnia,2214000.0,Yes,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,NaN,NaN,Yes,MongoDB;MySQL;PostgreSQL,Firebase Realtime Database;MongoDB,MongoDB,NaN,NaN,Yes,Datadog;Firebase;npm;pnpm,Amazon Web Services (AWS);Firebase;npm;pnpm;Vite,Firebase;npm;pnpm,NaN,NaN,Yes,Next.js;Node.js;React,Next.js;Node.js;React,Next.js;Node.js;React,NaN,Solid.js,Yes,Visual Studio Code,Visual Studio Code;Windsurf,Visual Studio Code,NaN,NaN,Google Gemini,Google Gemini;Shadcn/ui,Google Gemini,NaN,NaN,MacOS;Android,MacOS,GitHub;GitLab;Jira,GitHub;GitLab;Jira,GitHub;GitLab;Jira,NaN,NaN,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,NaN,NaN,Yes,Gemini (Flash general purpose models);openAI G...,Gemini (Flash general purpose models);Gemini (...,Gemini (Flash general purpose models);openAI G...,NaN,NaN,Not sure/can't remember,A few times per week,Between 5 and 10 years,"Infrequently, less than once per year",Chat (people);Videos;Lists of recommendations ...,3.0,NaN,4.0,5.0,1.0,2.0,7.0,9.0,11.0,15.0,NaN,Neutral,About half of the time,"Yes, I use AI tools daily",Favorable,Somewhat trust,Neither good or bad at handling complex tasks,Documenting code;Debugging or fixing code;Test...,NaN,Project planning;Committing and reviewing code...,Learning about a codebase;Writing code;Generat...,NaN,"AI solutions that are almost right, but not qu...",No,"Yes, I use AI agents at work weekly","Yes, somewhat",Software engineering,Multi-platform search enablement,AI agents have increased my productivity.;AI a...,AI agents have improved the quality of my code...,AI agents have improved collaboration within m...,NaN,NaN,It takes significant time and effort to learn ...,My company's IT and/or InfoSec teams have stri...,NaN,I am concerned about the accuracy of the infor...,NaN,Redis,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0

In [81]:
# survey.info()

In [54]:
survey.columns

Index(['ResponseId', 'MainBranch', 'Age', 'EdLevel', 'Employment',
       'EmploymentAddl', 'WorkExp', 'LearnCodeChoose', 'LearnCode',
       'LearnCodeAI',
       ...
       'AIAgentOrchestration', 'AIAgentOrchWrite', 'AIAgentObserveSecure',
       'AIAgentObsWrite', 'AIAgentExternal', 'AIAgentExtWrite', 'AIHuman',
       'AIOpen', 'ConvertedCompYearly', 'JobSat'],
      dtype='str', length=172)

In [1]:
#list(survey.columns)

In [56]:
schema.head(20)

,qid,qname,question,type,sub,sq_id
0,QID18,TechEndorse_1,What attracts you to a technology or causes yo...,RO,AI integration or AI Agent capabilities,1.0
1,QID18,TechEndorse_2,What attracts you to a technology or causes yo...,RO,Easy-to-use API,2.0
2,QID18,TechEndorse_3,What attracts you to a technology or causes yo...,RO,Robust and complete API,3.0
3,QID18,TechEndorse_4,What attracts you to a technology or causes yo...,RO,Customizable and manageable codebase,4.0
4,QID18,TechEndorse_5,What attracts you to a technology or causes yo...,RO,Reputation for quality,5.0
5,QID18,TechEndorse_6,What attracts you to a technology or causes yo...,RO,Connected to an open-source project,6.0
6,QID18,TechEndorse_7,What attracts you to a technology or causes yo...,RO,Good brand and public image,7.0
7,QID18,TechEndorse_8,What attracts you to a technology or causes yo...,RO,Reliability and low latency,8.0
8,QID18,TechEndorse_9,What attracts you to a technology or causes yo...,RO,Costs are manageable,9.0
9,QID18,TechEndorse_13,What attracts you to a technology or causes yo...,RO,Other (please specify):,10.0
10,QID18,TechEndorse_13_TEXT,What attracts you to a technology or causes yo...,RO,Other (please specify): - Text,13.0
11,QID19,TechOppose_1,What would turn you off or cause you to reject...,RO,Lack of AI or AI agents,1.0
12,QID19,TechOppose_2,What would turn you off or cause you to reject...,RO,Poor usability,2.0
13,QID19,TechOppose_3,What would turn you off or cause you to reject...,RO,Lack of or sub-par API,3.0
14,QID19,TechOppose_5,What would turn you off or cause you to reject...,RO,Inefficient or time-costly,4.0
15,QID19,TechOppose_7,What would turn you off or cause you to reject...,RO,Prohibitive pricing,5.0
16,QID19,TechOppose_9,What would turn you off or cause you to reject...,RO,Security or privacy concerns,6.0
17,QID19,TechOppose_11,What would turn you off or cause you to reject...,RO,Availability of better alternatives,7.0
18,QID19,TechOppose_13,What would turn you off or cause you to reject...,RO,Outdated or obsolete technology or features,8.0
19,QID19,TechOppose_16,What would turn you off or cause you to reject...,RO,Ethical concerns,9.0

In [57]:
schema.info()

<class 'pandas.DataFrame'>
RangeIndex: 139 entries, 0 to 138
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   qid       139 non-null    str
 1   qname     139 non-null    str
 2   question  139 non-null    str
 3   type      139 non-null    str
 4   sub       49 non-null     str
 5   sq_id     49 non-null     float64
dtypes: float64(1), str(5)
memory usage: 6.6 KB

In [58]:
# Завдання 1. Підрахунок загальної кількості респондентів
print(f"Загальна кількість респондентів: {survey['ResponseId'].nunique()}")

Загальна кількість респондентів: 49191

In [59]:
# Перевірка що 1 рядок = 1 респондент

print(f"Survey: {len(survey):} rows")

Survey: 49191 rows

In [60]:
# Завдання 2. Аналіз повноти відповідей респондентів
questions = set(schema["qname"].unique()) & set(survey.columns) #set - зберігає унікальні значення
complete_responses = survey[list(questions)].dropna().shape[0]
print(f"Респонденти, що відповіли на всі запитання: {len(questions):,} ")

Респонденти, що відповіли на всі запитання: 126

In [61]:
# Завдання 3. Статистичний аналіз досвіду респондентів

In [62]:
workexp = survey["WorkExp"]

mean_value = workexp.mean()
median_value = workexp.median()
mode_value = workexp.mode()[0]

result = pd.Series({
    "mean": round(mean_value), 
    "median": round(median_value),
    "mode": round(mode_value)
})
# pandas за замовчуванням ігнорує NaN, тому NaN не впливають на обчислення
result

mean      13
median    10
mode      10
dtype: int64

In [63]:
# Завдання 4. Аналіз віддаленої роботи
remote_count = survey[survey["RemoteWork"] == "Remote"].shape[0]
print(f"Респонденти, що працюють віддалено: {(remote_count):} ")
# remote_count = (survey["RemoteWork"] == "Remote").sum() схожий розрахунок

Респонденти, що працюють віддалено: 10931

In [64]:
# Продивлюсь значення колонок чи првильно я відфільтрувала
survey["RemoteWork"].value_counts()

RemoteWork
Remote                                                                          10931
Hybrid (some remote, leans heavy to in-person)                                   6732
In-person                                                                        6042
Hybrid (some in-person, leans heavy to flexibility)                              5831
Your choice (very flexible, you can come in when you want or just as needed)     4244
Name: count, dtype: int64

In [65]:
# Завдання 5. Визначення популярності Python
# Продивлюсь, що являє собою ця колонка
survey["LanguageHaveWorkedWith"].value_counts()

LanguageHaveWorkedWith
HTML/CSS;JavaScript;TypeScript                                                                370
Python                                                                                        229
C#;HTML/CSS;JavaScript;SQL;TypeScript                                                         193
HTML/CSS;JavaScript;PHP;SQL                                                                   180
Python;SQL                                                                                    169
                                                                                             ...
Bash/Shell (all shells);Dart;Go;HTML/CSS;Java;Lua;PHP;Rust;SQL                                  1
Bash/Shell (all shells);C;HTML/CSS;Java;JavaScript;Kotlin;Lua;Python;Rust;TypeScript;Zig        1
Bash/Shell (all shells);C#;C++;GDScript;HTML/CSS;JavaScript;Python;Rust;SQL;Zig;Mojo;Gleam      1
Bash/Shell (all shells);HTML/CSS;Lisp;PowerShell;Python                                         1
Assembly;C#;Go;Java;JavaScript;Rust                                                             1
Name: count, Length: 15478, dtype: int64

In [82]:
# Беремо колонку з мовами
languages = survey["LanguageHaveWorkedWith"]

# Перевіряємо, чи є Python у рядку (True для тих, у кого є Python) 
python_lang = languages.str.contains("Python", na=False,case=False) 
# case=False захистить, якщо Pyton буде з маленької літери

# Обчислюємо відсоток
python_percent = python_lang.mean() * 100  # mean() працює, бо True=1, False=0
# python_lang виглядає, як [True, False, True, True, False] → [1, 0, 1, 1, 0]
# .mean() рахує середнє значення:
# Наприклад (1 + 0 + 1 + 1 + 0) / 5 = 3 / 5 = 0.6

# Округлюємо до 1 знаку після коми
python_percent = round(python_percent, 1)
print("Відсоток респондентів, які програмують на Python:"f"{python_percent}%")

Відсоток респондентів, які програмують на Python:37.5%

In [67]:
# Завдання 6. Аналіз шляхів навчання програмуванню
# Шукаю в яких назвах колонок йдеться про навчатьння
[col for col in survey.columns if "learn" in col.lower()]

['LearnCodeChoose', 'LearnCode', 'LearnCodeAI', 'AILearnHow']

In [68]:
# По черзі перевіряю їх зміст та знаходжу потрібну
# survey["LearnCodeChoose"].value_counts()

In [69]:
survey["LearnCode"].value_counts(3)

LearnCode
Other online resources (e.g. standard search, forum, online community);Stack Overflow or Stack Exchange;Technical documentation (is generated for/by the tool or system)                                                                                                                                                                                                                                      0.018834
Other online resources (e.g. standard search, forum, online community);Technical documentation (is generated for/by the tool or system)                                                                                                                                                                                                                                                                       0.013857
Online Courses or Certification (includes all media types)                                                                                                                                                                                                                                                                                                                                                    0.012069
Other online resources (e.g. standard search, forum, online community);Stack Overflow or Stack Exchange;Technical documentation (is generated for/by the tool or system);AI CodeGen tools or AI-enabled apps                                                                                                                                                                                                  0.011831
AI CodeGen tools or AI-enabled apps                                                                                                                                                                                                                                                                                                                                                                           0.011533
                                                                                                                                                                                                                                                                                                                                                                                                                ...
Other online resources (e.g. standard search, forum, online community);Videos (not associated with specific online course or certification);Stack Overflow or Stack Exchange;Technical documentation (is generated for/by the tool or system);Coding Bootcamp;Games or coding challenges                                                                                                                      0.000030
Books / Physical media;Stack Overflow or Stack Exchange;Technical documentation (is generated for/by the tool or system);AI CodeGen tools or AI-enabled apps;Coding Bootcamp                                                                                                                                                                                                                                  0.000030
Other online resources (e.g. standard search, forum, online community);Books / Physical media;Videos (not associated with specific online course or certification);Stack Overflow or Stack Exchange;Technical documentation (is generated for/by the tool or system);Colleague or on-the-job training;Blogs or podcasts;Coding Bootcamp;Games or coding challenges;School (i.e., University, College, etc)    0.000030
Online Courses or Certification (includes all media types);Other online resources (e.g. standard search, forum, online community);Books / Physical media;AI CodeGen tools or AI-enabled apps;Colleague or on-the-job training                                                                                                                                                                                 0.000030
Online Courses or Certification (includes all media types);Stack Overflow or Stack Exchange;Blogs or podcasts;Games or coding challenges;School (i.e., University, College, etc)                                                                                                                                                                                                                              0.000030
Name: proportion, Length: 2767, dtype: float64

In [70]:
# survey["LearnCodeAI"].value_counts()

In [71]:
# survey["AILearnHow"].value_counts()

In [83]:
# Це поле LearnCode
# contains - враховано можливість множинних відповідей, тобто ми вибираємо а не точно вказуємо назву, як ==
online_courses = survey["LearnCode"].str.contains("Online Courses", na=False,case=False)
 
online_courses_count = online_courses.sum()

#online_courses_count
print("Кількість респондентів, які навчалися програмувати через онлайн курси: "f"{online_courses_count}")

Кількість респондентів, які навчалися програмувати через онлайн курси: 10973

In [86]:
# Завдання 7. Географічний аналіз компенсації Python-розробників

#  Фільтруємо Python-розробників
python_dev = survey[survey["LanguageHaveWorkedWith"].str.contains("Python", na=False,case=False)]
# Спочатку створюється список з True/False, потім відбираємо в список тільки з True, тому survey[survey[
print(f"ConvertedCompYearly до фільтрації: {len(python_dev):} ")

# Видаляємо пропуски в стовпчику компенсації ConvertedCompYearly
python_dev = python_dev.dropna(subset=["ConvertedCompYearly"])
print(f"ConvertedCompYearly після фільтрації: {len(python_dev):} ")

# Групуємо по країнах і рахуємо метрики
result = python_dev.groupby("Country")["ConvertedCompYearly"].agg(
    mean_comp= "mean",
    median_comp="median"
).round(0).reset_index()

result

ConvertedCompYearly до фільтрації: 18466
ConvertedCompYearly після фільтрації: 12765

                                  Country  mean_comp  median_comp
0                             Afghanistan    22329.0       1000.0
1                                 Albania    47218.0      50000.0
2                                 Algeria    20187.0       7088.0
3                                 Andorra   226104.0     226104.0
4                     Antigua and Barbuda        1.0          1.0
..                                    ...        ...          ...
148  Venezuela, Bolivarian Republic of...     9909.0       3000.0
149                              Viet Nam   218837.0       8254.0
150                                 Yemen    32930.0      23672.0
151                                Zambia     5424.0       3206.0
152                              Zimbabwe    34000.0      25500.0

[153 rows x 3 columns]

In [74]:
# Завдання 8. Аналіз освіти найбільш оплачуваних спеціалістів

# Перевіряємо ResponseId на дублікати на нулі
resp_duplicates= survey["ResponseId"].duplicated()
print(f"Total duplicate rows: {resp_duplicates.sum():,}")
resp_null= survey["ResponseId"].isnull()
print(f"Total null rows: {resp_null.sum():,}")

# Видаляємо пропуски
survey_comp = survey.dropna(subset=["ConvertedCompYearly"])
# Сортуємо по зарплаті (від більшої до меншої)
top5 = survey_comp.sort_values(by="ConvertedCompYearly", ascending=False).head(5)
# Дивимось рівень освіти
top5[["ConvertedCompYearly", "EdLevel","Country"]] # Country - просто цікаво по країнам

Total duplicate rows: 0
Total null rows: 0

,ConvertedCompYearly,EdLevel,Country
34267,50000000.0,"Associate degree (A.A., A.S., etc.)",United States of America
28700,33552715.0,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Ukraine
43143,18387548.0,"Associate degree (A.A., A.S., etc.)",Poland
35353,15430267.0,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Iran, Islamic Republic of..."
45971,13921760.0,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Netherlands

In [75]:
# Мені цікаво: Я бачу якісь дуже великі суми, можливо аномальні викиди
# Тому прибрала екстремальні значення
#  Беремо колонку ConvertedCompYearly
comp = survey["ConvertedCompYearly"].dropna()
# Рахуємо вищу межу
high = comp.quantile(0.95)
# 3. Фільтруємо
filtered = survey[
        (survey["ConvertedCompYearly"] <= high)
]
# Відфільтрую лише унікальні значення зарплати, тому що пробувала без фільтра, видає однакові значачення
top_5_quant = filtered.drop_duplicates(subset=["ConvertedCompYearly"])\
                      .sort_values(by="ConvertedCompYearly", ascending=False)\
                      .head(10)
# Виводимо потрібні колонки
top_5_quant[["ConvertedCompYearly", "EdLevel","Country"]]
# Можливо це більш реалістичні топ 5 компенсацій

,ConvertedCompYearly,EdLevel,Country
3060,232029.0,Some college/university study without earning ...,Germany
3160,232000.0,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",United States of America
12291,231880.0,Some college/university study without earning ...,United States of America
4878,231441.0,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",United Kingdom of Great Britain and Northern I...
5520,231150.0,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",United States of America
17085,231000.0,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",United States of America
376,230000.0,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",United States of America
28224,229819.0,Some college/university study without earning ...,Canada
14363,229748.0,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Romania
32675,229709.0,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Austria

In [76]:
# Цікаво подивитися розподіл виплат
filtered["ConvertedCompYearly"].value_counts().head(10)

ConvertedCompYearly
69609.0     328
58007.0     270
92812.0     269
81210.0     266
116015.0    263
150000.0    235
200000.0    220
120000.0    203
46406.0     198
100000.0    193
Name: count, dtype: int64

In [77]:
# Завдання 9. Аналіз популярності Python по віковим категоріям 

# Подивимось колонку 'Age' по віковим категоріям
survey['Age'].value_counts()

Age
25-34 years old      16519
35-44 years old      13241
18-24 years old       9210
45-54 years old       6275
55-64 years old       2626
65 years or older      942
Prefer not to say      378
Name: count, dtype: int64

In [78]:
# Перевіримо 
survey['Age'].isna().sum()

np.int64(0)

In [79]:

# Створюємо нову булеву колонку 'python_lang', де True - це входить Python
survey['python_lang'] = survey['LanguageHaveWorkedWith'].str.contains("Python", na=False,case=False)
# survey['python_lang']
result = (
    survey
    .groupby('Age')['python_lang']
    .mean() # Рахуємо середнє значення (mean = (1 + 0 + 1) / 3 = 0.67)
    .mul(100) # Множимо на 100
    .reset_index()
    .rename(columns={'python_lang': 'python_percent'})
)
# Округлимо
result['python_percent'] = result['python_percent'].round(2)

print(result)

                 Age  python_percent
0    18-24 years old           40.00
1    25-34 years old           36.94
2    35-44 years old           36.72
3    45-54 years old           38.63
4    55-64 years old           37.24
5  65 years or older           31.63
6  Prefer not to say           31.22

In [80]:
# Завдання 10. Аналіз індустрій серед високооплачуваних віддалених працівників
comp = survey["ConvertedCompYearly"].dropna()
# Рахуємо вищу межу
high = comp.quantile(0.75)
# 3. Фільтруємо
filtered = survey[
        (survey["ConvertedCompYearly"] >= high)&(survey["RemoteWork"] == "Remote")]

industry = filtered["Industry"].value_counts().head(10)

industry = industry.reset_index()
industry.columns = ["Industry", "Count"]
# Дивимось 
print(industry)

                                     Industry  Count
0                        Software Development   1186
1                                     Fintech    190
2                                  Healthcare    188
3                                      Other:    176
4  Internet, Telecomm or Information Services    138
5                  Banking/Financial Services     88
6                                  Government     78
7                Media & Advertising Services     75
8                Retail and Consumer Services     65
9             Transportation, or Supply Chain     63